- README.md
- c-scape/src/c.rs
- examples/test-workdir.rs
- tests/tests.rs
> Implement getcwd and chdir

- c-scape/src/data/linux_gnu.rs
- c-scape/src/data/mod.rs
- c-scape/src/lib.rs
fixes #56, along with everything else.
> implement sched_getaffinity

- c-scape/src/lib.rs
- origin/src/lib.rs
This adds several comments to the assembly code for `_start`.
> Add comments to `_start`.

- README.md
- c-scape/src/at_fork.rs
- c-scape/src/error_str.rs
- c-scape/src/use_libc.rs
This adds a few documentation comments, and updates the documentation in
the README.md file.
> Add documentation comments.

- Cargo.toml
- origin/src/threads.rs
Add more logging to `join` and `detach` for threads.
> Add logging to thread deallocation.

- README.md
- c-scape/src/threads/mod.rs
- origin/src/sync/condvar.rs
- origin/src/sync/futex.rs
- origin/src/sync/mod.rs
- tests/sync-barrier.rs
- tests/sync-condvar.rs
- tests/sync-mutex.rs
> Implement pthread_cond*.

- c-scape/src/malloc/mod.rs
This isn't required by the relevant standards, but existing code in the
wild depends on this.
> Make `malloc(0)` return a non-NULL pointer.

- c-scape/src/lib.rs
As the title says. Adds a small part of the `prctl` API.
> Add `prctl` parent death signal and dumpability

- c-gull/Cargo.toml
- c-scape/Cargo.toml
- origin/Cargo.toml
And errno 0.3 and linux-raw-sys 0.3.
> Update to rustix 0.37.

- .github/workflows/main.yml
- c-gull/src/nss.rs
- c-gull/src/use_libc.rs
- c-scape/src/lib.rs
- c-scape/src/use_libc.rs
- origin/README.md
- origin/src/lib.rs
- tests/examples.rs
- tests/sync-mpsc-sync.rs
- tests/thread.rs
This involves updating a few tests, and fixing `checked_cast` to handle null pointers properly.
> Update to nightly-2023-03-17.

- c-scape/src/io/mod.rs
- c-scape/src/io/timerfd.rs
- c-scape/src/lib.rs
These are needed to run async-std demos.
> Add timerfd and SYS_epoll_create1 support.

- c-gull/Cargo.toml
- c-scape/Cargo.toml
- c-scape/src/net/mod.rs
- origin/Cargo.toml
Implment the `SO_ERROR` socket option.
> Implement `SO_ERROR`.

- c-scape/src/fs/utime.rs
> Implement `lutimes` and `utimes`.

- c-scape/src/fs/inotify.rs
- c-scape/src/fs/mod.rs
> Implement `inotify_*`.

- c-gull/Cargo.toml
- c-scape/Cargo.toml
- c-scape/src/process/mod.rs
- c-scape/src/process/umask.rs
- c-scape/src/time/mod.rs
- origin/Cargo.toml
This depends on rustix patches which aren't released yet.
> Implement `umask` and `settime`.

- .github/workflows/main.yml
- origin/src/sync/condvar.rs
- origin/src/sync/futex.rs
- origin/src/sync/futex_rwlock.rs
- origin/src/sync/mod.rs
- origin/src/sync/wait_wake.rs
- tests/fs.rs
Update some tests, source files, and target descriptions to the latest Rust versions.
This is like #191, but doesn't include the target spec changes.
> Update several things to the latest upstream sources

- c-scape/src/signal/mod.rs
`unimplemented` can end up re-invoking `abort`. So instead, use `rustix` calls exclusively to abort the process.
> Don't use `unimplemented!` in the `abort` implementation.

- c-gull/Cargo.toml
- c-scape/Cargo.toml
- c-scape/src/io/mod.rs
- c-scape/src/net/mod.rs
- c-scape/src/process/egid.rs
- c-scape/src/process/euid.rs
- c-scape/src/process/gid.rs
- c-scape/src/process/pid.rs
- c-scape/src/process/sid.rs
- origin/Cargo.toml
And misc cleanups in the *id.rs source files.
> Implement `getset`.

- README.md
- Add links to programs ported to mustang
- Add documentation about panic = "abort"
- Document some more known limitations
> Add more README content.

- tests/lazy.rs
- tests/sync-lazy_lock.rs
- tests/sync-mpsc-sync.rs
- tests/sync-mpsc.rs
- tests/sync-mutex.rs
- tests/sync-once.rs
- tests/sync-once_lock.rs
- tests/sync-rwlock.rs
- tests/thread.rs
These tests no longer segfault, so re-enable them.
> Re-enable panic tests on 32-bit x86.

- .github/workflows/main.yml
- Cargo.toml
- target-specs/i686-mustang-linux-gnu.json
- target-specs/x86_64-mustang-linux-gnu.json
- tests/examples.rs
- tests/fs.rs
- tests/net-ip.rs
- tests/process.rs
- tests/sync-rwlock.rs
Update to c-gull 0.15.41, Rust nightly-2024-02-26, and so on.
> Update dependency versions.
