c-scape/Cargo.toml
c-scape/src/c.rs

As proposed in #5. This is just a straightforward code replacement, I'm not sure what else if anything needs to be done. I've left `bcmp` as-is since I can't see any reason to use `compiler_builtins` there.

Use compiler_builtins for mem{cmp,cpy,move,set}

---

c-scape/Cargo.toml
c-scape/src/c.rs

See #5.
Note: I've changed the signatures of `memchr` and `memrchr` to match the (weird) C signatures, which take a const pointer but return a mut pointer ([e.g.](https://man7.org/linux/man-pages/man3/memchr.3p.html)).

Call out to the memchr crate for memchr and memrchr

---

c-scape/Cargo.toml
c-scape/src/c.rs
c-scape/src/lib.rs
tests/tests.rs

Referencing "memcpy" and other symbols from `__mustang_c_scape__c`
didn't turn out to be sufficient to ensure they'd be linked in from
compiler-builtins, and not from the host libc.
Switch back to explicitly defining `memcpy` etc., though still use
compiler-builtins to do the work. This requires us to use
`#[feature(rustc_private)]` for now, but fortunately the things we're
depending on should be relatively stable in practice.
Also add a test for this.

Go back to explicitly defining `memcpy` etc.

---

.github/workflows/main.yml
README.md
c-scape/Cargo.toml
c-scape/src/c.rs
c-scape/src/data/linux_gnu.rs
c-scape/src/data/mod.rs
examples/net-addr.rs
examples/net-ip.rs
examples/net-tcp.rs
examples/net-udp.rs
tests/tests.rs

This implements enough of `getaddrinfo`, `freeaddrinfo`, `gai_strerror`,
`gethostname`, `getsockopt`, and `setsockopt` to pass all of `std`'s
in-tree tests that don't use threads.
Fixes #21.

Basic networking support.

---

Cargo.toml
c-scape/Cargo.toml
c-scape/README.md
c-scape/src/c.rs
c-scape/src/data/linux_gnu.rs
c-scape/src/data/mod.rs
c-scape/src/lib.rs
c-scape/src/pthread.rs
mustang/Cargo.toml
mustang/README.md
mustang/src/lib.rs
origin/Cargo.toml

The `dlmalloc` crate is a port of the dlmalloc library to Rust.
`wee_alloc` is specialized for small code size. Retain it as an option,
but use `dmalloc` by default, as it's a general-purpose allocator.
Also, move the `#[global_allocator]` code out of c-scape and into
mustang, as the roles for these crates are emerging. c-scape is focused
on providing C ABI compatibility, while mustang is focused on pulling
together all the pieces to support the *-mustang-* targets.
Fixes #28.

Use `dlmalloc` as the default allocator.

---

README.md
examples/empty.rs
examples/hello.rs
examples/rust-by-example-threads.rs
examples/test-args.rs
examples/test-ctor.rs
examples/test-environ.rs
examples/test-simd.rs
examples/test-tls.rs
examples/test-workdir.rs
mustang/README.md
mustang/src/lib.rs
tests/env.rs
tests/examples.rs
tests/fs.rs
tests/net-addr.rs
tests/net-ip.rs
tests/net-tcp.rs
tests/net-udp.rs
tests/thread-local.rs
tests/thread.rs
tests/time.rs

Mustang isn't just about compiling programs, it's about running them
too! 😀

Rename `mustang::can_compile_this` to `mustang::can_run_this`.

---

README.md
c-scape/src/c.rs
c-scape/src/exit.rs
c-scape/src/pthread.rs
origin/Cargo.toml
origin/README.md
origin/src/arch-aarch64.rs
origin/src/arch-riscv64.rs
origin/src/arch-x86.rs
origin/src/arch-x86_64.rs
origin/src/lib.rs
origin/src/program.rs
origin/src/threads.rs

Rename `thread_data` variables to `thread`, to reflect that what used to
be `ThreadData` is now `Thread`. And tidy up other documentation and
comments.

Rename `Thread::stack` to a `thread_stack` free function, and more tidying.

---

.github/workflows/main.yml
origin/Cargo.toml
origin/src/arch-aarch64.rs
origin/src/arch-riscv64.rs
origin/src/arch-x86.rs
origin/src/arch-x86_64.rs
origin/src/lib.rs
origin/src/program.rs
origin/src/threads.rs

Origin's threading code can work on non-`mustang` targets, and with a
little extra code, it can use `libc` for `exit`/`atexit`, and be
minimally usable on non-`mustang`.
The main purpose of this, though, is to make the generated API
documentation for non-custom targets useful.

Make `origin` usable on non-`mustang` targets.

---

c-scape/COPYRIGHT
c-scape/LICENSE-APACHE
c-scape/LICENSE-Apache-2.0_WITH_LLVM-exception
c-scape/LICENSE-MIT
c-scape/README.md
mustang/COPYRIGHT
mustang/LICENSE-APACHE
mustang/LICENSE-Apache-2.0_WITH_LLVM-exception
mustang/LICENSE-MIT
mustang/README.md
origin/COPYRIGHT
origin/LICENSE-APACHE
origin/LICENSE-Apache-2.0_WITH_LLVM-exception
origin/LICENSE-MIT
origin/README.md

In preparation for publishing the crates on crates.io, add more complete
README files, as well as license files.

Add standalone READMEs and license files to the individual crates.

---

c-scape/src/lib.rs
origin/src/arch-aarch64.rs
origin/src/arch-arm.rs
origin/src/arch-riscv64.rs
origin/src/arch-x86.rs
origin/src/arch-x86_64.rs
origin/src/program.rs
origin/src/threads.rs

Change origin's APIs which take callsbacks to take `Box<dyn FnOnce()>`
instead of `unsafe extern "C"` functions with `*mut c_void` callbacks,
so that `at_exit` and similar functions can be safe.
This also simplifies the `clone` assembly code sequences, as they no
longer need to pass a separate `arg` argument through, which previously
meant storing it on the child stack on some architectures.
It does, however, mean we double-`Box`, once to box up the `dyn Any`
object and another box so that we can get a single non-fat pointer to
it. If Rust ever gains a way to manipulate the raw parts of a fat
pointer and pass them through assembly code we might be able to avoid
this outer `Box`, but at present, double-`Box`ing seems to be the
recommended way.

Use `FnOnce` functions instead of `unsafe extern "C"` functions.

---

c-scape/src/lib.rs

this implements the tagging mentioned in https://github.com/sunfishcode/mustang/pull/59#issuecomment-955057932, to simplify the implementation of malloc.
`tagged_alloc`, `get_layout` and `tagged_dealloc` where seperately checked for correctness using miri.
also changed `posix_memalign` to be closer to its behavior in libc.

replace hashmap with tagged allocations for tracking allocation layout

---

README.md
c-scape/Cargo.toml
c-scape/README.md
c-scape/src/data/linux_gnu.rs
c-scape/src/error_str.rs
c-scape/src/lib.rs
mustang/Cargo.toml
origin/Cargo.toml
origin/src/arch-aarch64.rs
origin/src/arch-arm.rs
origin/src/arch-riscv64.rs
origin/src/arch-x86.rs
origin/src/arch-x86_64.rs
origin/src/mutex.rs
origin/src/program.rs
origin/src/threads.rs

The rsix crate is renamed to rustix, and there are a few minor API changes:
`SocketAddr` is now `SocketAddrAny` to avoid ambiguity with
`std::net::SocketAddr`, and some "runtime" APIs switched from `c_char` to `u8`.

Update to rustix 0.26.0.

---

c-scape/src/lib.rs
mustang/Cargo.toml
mustang/src/lib.rs
specs/aarch64-mustang-linux-gnu.json
specs/riscv64gc-mustang-linux-gnu.json
tests/lazy.rs
tests/sync-mpsc.rs
tests/sync-mutex.rs
tests/sync-once.rs
tests/sync-rwlock.rs
tests/thread.rs

the version of `gimli` needed has been released and `unwinding` has been updated to use it

restore unwinding support for aarch64 and riscv64

---

README.md
tests/process.rs

fixes #34, since this is the last step mentioned.
the cause of the failure in `smoke_failure` and `test_process_output_fail_to_start` is unrelated to mustang, wriiten https://github.com/rust-lang/rust/issues/90825 for that
it also seems that test commands that don't  include `--target=specs/x86_64-mustang-linux-gnu.json` are not actually testing mustang
(can be verified by modifying `c-scape` and then running the commands with the given enviroment variables).
it also seems that commands that contain `--target=specs/x86_64-mustang-linux-gnu.json` don't actually build on the desired architecture, since according to [the cargo reference](https://doc.rust-lang.org/cargo/reference/config.html#buildtarget) the argument `--target` overrides `CARGO_BUILD_TARGET`.
(can be verified by adding a …

Add tests for process

---

c-scape/src/data/linux_gnu.rs
c-scape/src/data/mod.rs
c-scape/src/lib.rs

This is a simple wrapper around `rustix::io::ioctl_tiocgwinsz`.

Implement the `TIOCGWINSZ` ioctl.

---

README.md

Mustang completely replaces libc, but it doesn't yet have all the
features of a libc, in particular the "top half", which Rust code
doesn't use, but which is common to use from C.

Mention C libraries as a known limitation.

---

README.md

Mustang currently intends to support all Linux versions that Rust does,
however at this time the only CI testing we have is on relatively recent
Linux versions, because that's what common CI providers provide.

Document mustang's Linux kernel version support.

---

.github/workflows/main.yml
tests/net-addr.rs
tests/net-tcp.rs

This re-enables the net-tcp and net-addr tests, which pass for me locally, to see what they do in CI.

Start investigating the failing tests

---

c-scape/Cargo.toml
c-scape/src/lib.rs

Like the libc crate, the errno crate is implemented in Rust and supports
no_std.

Use the errno crate for setting errno.

---

c-scape/src/lib.rs
c-scape/src/use_libc.rs

Now that mustang depends on the libc crate unconditionally, enable the
libc! macro checks by default.

Enable the `libc!` macros by default, and fix ensuing errors.

---

c-scape/Cargo.toml
c-scape/README.md

Keep in short and simple. Elaborate in the body of the README.md instead
of in the description itself.

Simplify c-scape's description.

---

.github/workflows/main.yml
Cargo.toml
README.md
build.rs
c-scape/Cargo.toml
c-scape/src/at_fork.rs
c-scape/src/error_str.rs
c-scape/src/lib.rs
mustang/Cargo.toml
mustang/src/allocator.rs
mustang/src/lib.rs
origin/Cargo.toml
origin/src/arch-aarch64.rs
origin/src/arch-arm.rs
origin/src/arch-riscv64.rs
origin/src/arch-x86.rs
origin/src/arch-x86_64.rs
origin/src/lib.rs
origin/src/mutex.rs
origin/src/program.rs
origin/src/threads.rs
specs/aarch64-mustang-linux-gnu.json
specs/armv5te-mustang-linux-gnueabi.json
specs/i686-mustang-linux-gnu.json
specs/riscv64gc-mustang-linux-gnu.json
specs/x86_64-mustang-linux-gnu.json
tests/examples.rs
tests/thread-local.rs

After a fork, the child only has one thread, and it looks like all the
other threads are suspended. This may leave behind locks in locked
states and cause deadlocks, however deadlocks are not considered unsafe.
Consequently, fork doesn't need to be unsafe.
This also changes the `on_fork` callback functions to be
`Box<Fn() + Send>` so that it's safe to call them, and adds code to
c-scape and non-mustang targets to wrap them as needed.

Move `fork` from origin to c_scape

---

c-scape/src/lib.rs
c-scape/src/use_libc.rs

implements compile time checks for casts by (ab)using `core::mem::transmute`,
successfully detected layout mismatch between `libc::stat` and `rustix::fs::Stat`, and between `libc::sockaddr` and `SocketAddrStorage` in i686,
and between pthread types of `libc` and of the crate in aarch64.
fixes #90

implement compile checked pointer casts for libc signiture check

---

c-scape/Cargo.toml
c-scape/src/lib.rs
origin/Cargo.toml

`Mode::from_bits` now requires the operand be masked to only include
mode bits, and `readv` now takes a `&mut` operand.

Update to rustix 0.32.0.

---

.github/workflows/main.yml
c-scape/src/lib.rs

Rust nightly now uses `openat` and `unlinkat`, so implement the C ABI
for these.

Implement `openat` and `unlinkat`.

---

c-scape/Cargo.toml
origin/Cargo.toml
origin/src/threads.rs

The only API change here is linux-raw-sys dropping its versioned
modules.

Update to rustix 0.33.0 and linux-raw-sys 0.0.40.

---

.github/workflows/main.yml
c-scape/Cargo.toml
c-scape/src/lib.rs
ci/getsockopt-timeouts.patch
ci/translate-errno.patch
origin/Cargo.toml

With bytecodealliance/rustix#219, rustix now returns addresses from some
socket functions wrapped in `Option`, to reflect the fact that some
network layers are unable to return sender or peer addresses.

Handle rustix APIs which return optional addresses.

---

c-scape/Cargo.toml
c-scape/src/lib.rs
origin/Cargo.toml

This updates for the rename from `BorrowedFd::borrow_raw_fd` to
`BorrowedFd::borrow_raw`.

Update to rustix 0.34.0 and io-lifetimes 0.6.0.

---

c-scape/src/lib.rs
origin/src/arch-x86.rs
origin/src/lib.rs
origin/src/program.rs
origin/src/threads.rs

To a first approximation, this makes origin and c-scape conform to
strict-provenance.

Avoid casting pointers to usize and back.

---

c-scape/aarch64_outline_atomics/aarch64_outline_atomics/src/lib.rs
c-scape/src/lib.rs
mustang/src/lib.rs
origin/src/lib.rs

Use `#![deny(fuzzy_provenance_casts)]` and `#![deny(lossy_provenance_casts)]`,
which disallow ptr2int and int2ptr casts, and fix a few casts which
remained after #106.

Enable the new strict-provenance lints.

---

c-scape/Cargo.toml
c-scape/src/fs/access.rs
c-scape/src/fs/chmod.rs
c-scape/src/fs/link.rs
c-scape/src/fs/mkdir.rs
c-scape/src/fs/mod.rs
c-scape/src/fs/open.rs
c-scape/src/fs/opendir.rs
c-scape/src/fs/readlink.rs
c-scape/src/fs/realpath.rs
c-scape/src/fs/remove.rs
c-scape/src/fs/rename.rs
c-scape/src/fs/stat.rs
c-scape/src/fs/symlink.rs
c-scape/src/io/dup.rs
c-scape/src/lib.rs
c-scape/src/net/mod.rs
c-scape/src/process/chdir.rs
origin/Cargo.toml
origin/src/program.rs
origin/src/threads.rs

- `ZStr` is renamed back to `CStr`.
- `page_size` and `init` have moved to `param`.
- `dup2`'s second argument is now `&mut OwnedFd`.

Update to rustix 0.35-6-beta.2.

---

c-scape/src/fs/realpath.rs
c-scape/src/lib.rs
c-scape/src/malloc/mod.rs
c-scape/src/mem/bstring.rs
c-scape/src/mem/mod.rs
c-scape/src/mem/string.rs
c-scape/src/net/mod.rs
c-scape/src/process/getcwd.rs

C-scape implements a `libc`-crate-compatible ABI. We use the `libc` crate
to provide the public interface to it, and just substitute in c-scape at
link time. Consequently, c-scape's functions don't need to be `pub`. And
it's cleaner if they aren't, because this ensures that all users use
c-scape consistently.

Make all functions in `c-scape` non-`pub`.

---

c-scape/src/malloc/mod.rs
origin/src/threads.rs
specs/aarch64-mustang-linux-gnu.json
specs/armv5te-mustang-linux-gnueabi.json
specs/i686-mustang-linux-gnu.json
specs/riscv64gc-mustang-linux-gnu.json
specs/x86_64-mustang-linux-gnu.json
tests/examples.rs

Fix an unused-variable warning in origin/src/threads.rs in release builds.
And remove the has-elf-tls keys from the target descriptions, which
are no longer needed. And re-enable stderr checking in the examples
test now that we no longer get warnings.

Fix warnings.

---

Cargo.toml
c-scape/Cargo.toml
c-scape/aarch64_outline_atomics/aarch64_outline_atomics/Cargo.toml
c-scape/src/lib.rs
mustang/Cargo.toml
origin/Cargo.toml
tests/fs.rs
tests/lazy.rs
tests/sync-barrier.rs
tests/sync-mpsc.rs
tests/sync-mutex.rs
tests/sync-once.rs
tests/sync-rwlock.rs
tests/thread.rs

Update tests/thread.rs and tests/sync-mutex.rs to the latest upstream, and fix unused-import warnings in tests. 
Also, update to Rust 2021 edition, as the updated tests depend on it.

Update some tests to the latest upstream

---

c-scape/src/net/mod.rs
c-scape/src/threads/mod.rs

This fixes most of the the pthread parts of #94.

Fix the layout of the pthread types on aarch64.

---

Cargo.toml
c-gull/COPYRIGHT
c-gull/Cargo.toml
c-gull/LICENSE-APACHE
c-gull/LICENSE-Apache-2.0_WITH_LLVM-exception
c-gull/LICENSE-MIT
c-gull/README.md
c-gull/src/lib.rs
c-gull/src/nss.rs
c-gull/src/printf.rs
c-gull/src/rand48.rs
c-gull/src/strtod.rs
c-gull/src/strtol.rs
c-gull/src/time.rs
c-gull/src/use_libc.rs
c-scape/Cargo.toml
c-scape/README.md
c-scape/src/at_fork.rs
c-scape/src/fs/opendir.rs
c-scape/src/fs/readlink.rs
c-scape/src/lib.rs
c-scape/src/threads/mod.rs
c-scape/src/use_libc.rs
mustang/Cargo.toml
mustang/src/lib.rs
test-crates/libc-replacement/Cargo.toml
test-crates/libc-replacement/README.md
test-crates/libc-replacement/src/main.rs
test-crates/mustang-macro-does-nothing/README.md

The relationship between c-scape and c-gull is:
- c-gull: uses std and c-scape.
- c-scape: does not use std.
This means c-scape can be used by std, and c-gull can't be. But it also
means that c-gull can easily implement many more C features. This PR adds:
- timezone functions using the tz-rs crate
- stdio functions using the printf-compat crate
- random functions using the rand crate
- nss functions using the getent command
c-gull is extraordinarily experimental.

Add a new c-gull crate, which is an above-std libc implementation.

---

examples/test-tls-dtors.rs
origin/src/program.rs
origin/src/threads.rs

When a program calls `exit`, run the TLS destructors in addition to the
regular program-wide destructors.

Call the TLS destructors on `exit`.

---

.github/workflows/main.yml
c-scape/src/lib.rs
c-scape/src/threads/mod.rs
tests/examples.rs

`untagged_unions` is no longer sufficient to have a `Drop` type in a
union, so wrap these fields in `ManuallyDrop`.
And it's no longer necessary to explicitly enable `core_c_str`.

Update Mustang to work with the latest nightly Rust.

---

c-scape/src/env/mod.rs
c-scape/src/lib.rs
c-scape/src/process/exec.rs
c-scape/src/process/mod.rs

The main thing I'm not sure about here is how we want to handle calling Rust functions from one module from another, such as the `environ` or `_getenv`. I think the move here is to reexport everything as `pub (crate)` or have some sort of crate only `imp` module that everything goes into, but I'm open to ideas.

Work on exec functions

---

.github/workflows/main.yml
c-scape/src/lib.rs
tests/examples.rs
tests/net-ip.rs

As mentioned in the issue #139, any code using threads fails to link. Since this commit, rust links against a pthread_setname_np on linux. Android is unaffected. https://github.com/rust-lang/rust/commit/013986be1bcfbfd9cedddf22dfd9584ccdb7ee6e

c-scape: add pthread_setname_np (#139)

---

c-gull/README.md
c-scape/Cargo.toml
c-scape/src/mem/bstring.rs

Don't use the memchr crate to implement `memchr`.

---

Cargo.toml
c-gull/Cargo.toml
c-scape/Cargo.toml
c-scape/src/rand48.rs
origin/Cargo.toml
test-crates/mustang-macro-does-nothing/README.md

This bumps libc to get the `rand48` definitions into mustang. I've also slightly refactored how `erand48` converts to a float in order to better distribute the bits randomly.

Rand48 fixes + libc bump

---

c-gull/Cargo.toml
mustang/Cargo.toml
mustang/src/lib.rs

c-gull is the part of mustang which depends on std, so start making it optional to enable no_std use cases.

Start making mustang's c-gull dependency optional.

---

c-scape/src/fs/mod.rs
c-scape/src/fs/sendfile.rs
c-scape/src/io/mod.rs
c-scape/src/io/splice.rs
tests/kernel_copy.rs

Adds splice and sendfile, as those got added sometime in when I last looked at this and now.
I'm very unsure of all the unsigned to signed conversions and back here, and I'm not really sure why `rustix` has offsets as unsigned here.
I've uncommented the tests, but strangely enough I don't think that tests actually tests the splice or sendfile path, as those appear locked behind benches. I will add some tests for this.

Add splice and sendfile

---

.github/workflows/main.yml
c-gull/Cargo.toml
c-gull/src/lib.rs
c-scape/src/rand48.rs
mustang/Cargo.toml
mustang/src/lib.rs
test-crates/mustang-nostd/Cargo.toml
test-crates/mustang-nostd/README.md
test-crates/mustang-nostd/src/main.rs

`c-scape` had an accidental dependance on `std::f64` which prevented compiling on no_std which is fixed by using `libm`.
Added feature support for `nostd` which exports `c_scape` rather than `c_gull` which still includes enough for a working `dlmalloc`/`unwinding`. I was able to compile and run a `no_std` executable with the following [program](https://github.com/jordanisaacs/snowfalldb/blob/main/src/main.rs). It also works if you use the `#[start]` feature. Build command is
```
cargo build --target=x86_64-mustang-linux-gnu -Zbuild-std=core,alloc 
```
In terms of documentation, not entirely sure what the `#[start]` is adding vs. directly implementing `main`. Also because `mustang` is controlling all of program startup we can probably determine the safety of the start function pretty …

Mustang nostd support

---

c-gull/Cargo.toml
c-gull/src/lib.rs
c-gull/src/resolve.rs
c-scape/Cargo.toml
c-scape/src/lib.rs
c-scape/src/net/mod.rs

Moves resolve into c-gull from c-scape as it requires `sync-resolve` which in turn requires std. Also, removes the net feature. This is because the rustix already was building net, and it simplifies the c-gull passthrough.

Move resolve into c-gull (and remove c-scape net feature)

---

.github/workflows/main.yml
origin/src/sync/wait_wake.rs
origin/src/threads.rs
test-crates/mustang-nostd/src/main.rs
tests/examples.rs

Origin fails to compile on latest nightly due to a [rename](https://github.com/rust-lang/rust/pull/107736_) of `as_mut_ptr` in the atomic ptr api. This fixes that to use `as_ptr`. Also updates the test toolchain to latest nightly.

Use updated atomic ptr api

---

Cargo.toml
tests/examples.rs

Should fix running tests when not using rustup for toolchain management. Closes https://github.com/sunfishcode/mustang/issues/161

Check if rustup is installed for tests

---

c-scape/src/io/epoll.rs
c-scape/src/io/mod.rs

Use the new epoll API from bytecodealliance/rustix#487.
Fixes #86.

Implement `epoll`

---

c-scape/src/process/kill.rs

This is needed to run tokio demos.

Implement `__libc_current_sigrtmax`.

---

c-scape/src/fs/mod.rs
c-scape/src/fs/xattr.rs

These aren't implemented in rustix yet, but these stubs should be enough to get simple things working.

Add stubs for `*getxattr` functions.

---

c-gull/src/lib.rs
c-gull/src/time.rs

This also revamps the time code, fixing the FIXMEs. This code is still experimental, but it is enough to support coreutils `date`, `pr`, and `touch`.

Implement `tzset`, `timegm`, and `timelocal`.

---

c-scape/src/lib.rs
c-scape/src/termios/mod.rs

These are somewhat untidy, as I now think rustix should do more work to unify `termios2` and `termios`. But this should work for now.

Implement `tcgetattr`, `cfmakeraw`, and `tcsetattr`.

---

mustang/target-specs/aarch64-mustang-linux-gnu.json

This is enabled in the target spec generated by
`rustc +nightly -Z unstable-options --print target-spec-json --target aarch64-unknown-linux-gnu`
so enable it for Mustang too.

Enable the `+v8a` feature on aarch64.

---

README.md
c-gull/Cargo.toml
c-scape/Cargo.toml
c-scape/src/lib.rs
c-scape/src/process/kill.rs
c-scape/src/signal/mod.rs
origin/Cargo.toml

This is highly experimental and doesn't actually work for installing actual signal handlers, but it is enough to allow `SIG_IGN` and `SIG_DFL` handlers to work.
Marking as a draft as this depends on unreleased rustix patches.
With this, everything in coreutils except `test_tmp_files_deleted_on_sigint` passes.

Improved `sigaction` support.

---

c-scape/src/signal/mod.rs
origin/src/threads.rs

Call `set_tid_address` to initialize the main thread's clear child tid address field.
And, avoid calling `gettid()` when the tid can be determined in other ways.

Call `set_tid_address` on the main thread.

---

c-gull/src/printf.rs
c-scape/src/process/exec.rs
c-scape/src/time/mod.rs
tests/process.rs

On Linux at least, `execveat` with a directory fd opened with `O_CLOEXEC` can't run programs that use `#!` such as shell scripts. So switch `execvp` back to allocating a buffer, using an `mmap` syscall so that it's safe to do in the child of a fork, and using plain `execve`.
Also, implement `difftime` and `__strncmp_chk`.

Fix `execvp` on shell scripts.

---

README.md
c-gull/README.md

Mention that coreutils' "unix" feature and bat's git2 support work. Elaborate on the known limitations. And fix out of date content in c-gull's README.

Add more content to the READMEs.

---

Cargo.toml
c-gull/Cargo.toml
c-gull/README.md
c-gull/src/use_libc.rs
c-scape/Cargo.toml
c-scape/README.md
c-scape/src/at_fork.rs
c-scape/src/env/mod.rs
c-scape/src/fs/dir/readdir.rs
c-scape/src/lib.rs
c-scape/src/process_.rs
c-scape/src/use_libc.rs
mustang/Cargo.toml
test-crates/libc-replacement/Cargo.toml

Add cargo features "take-charge" and "coexist-with-libc" to c-scape and c-gull, and use those features instead of testing for `target_vendor = "mustang"`.
This is similar to how origin was recently converted to use cargo features instead of `target_vendor = "mustang"` and will enable c-scape and c-gull to be used in more ways.

Use cargo features rather than `target_vendor` in c-scape and c-gull

---

README.md

Add a mention of the new [Eyra] project to Mustang's README. Mustang is still maintained; all of Mustang's main libraries have been factored out, so Mustang proper is now just a very thin layer that just sets up the custom target and pulls in all the needed libraries.
Eyra is using uses those same libraries, just without Mustang's custom target, so it's more convenient to use in some situations.
While here, fix the command-line example that enables the `env_logger` feature; to get log output, it's also necessary to enable the `log` feature.
[Eyra]: https://github.com/sunfishcode/c-ward/tree/main/eyra

Add a mention of the new Eyra project to Mustang's README.

---

.github/workflows/main.yml
mustang/Cargo.toml
mustang/src/lib.rs

Move the code from Mustang for enabling unwinding's features, as the c-scape crate how handles that automatically.
While here, update to the latest QEMU.

Update to the latest c-scape, which enables unwinding features.

---

mustang/Cargo.toml

Just depend on c-gull, which pulls in everything it needs automatically.

Remove the direct dependency on origin.

---

README.md

- 32-bit arm isn't listed as supported, so don't mention its limitations.
- `catch_unwind` now does work on 32-bit x86.
- Mustang supports "static PIC" now, via "experimental-relocate".

Update the known limitations.

---

.github/workflows/main.yml
README.md
example-crates/mustang-example-lto/Cargo.toml
example-crates/mustang-example-lto/README.md
example-crates/mustang-example-lto/src/main.rs

Update to c-gull 0.15.10, which fixes LTO compatibility. Add an example that uses LTO, and test it in the example-crates test.

Enable LTO support.

---

.github/actions/install-rust/action.yml
.github/workflows/main.yml
Cargo.toml
README.md
example-crates/mustang-custom-allocator/Cargo.toml
example-crates/mustang-example-lto/Cargo.toml
example-crates/mustang-example/Cargo.toml
example-crates/mustang-nostd/Cargo.toml
examples/test-simd.rs
tests/examples.rs

This obviates the 'debug = false' workaround.
Disable the core_simd tests for now.

Update to the latest c-gull and Rust nightly.
